spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/web-sys-app?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
        username: web-finance-app
        password: a.123456
    jpa: 
        show-sql: true
        hibernate:
            ddl-auto: create
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
server:
    port: 8001